### PR TITLE
fixup for ::before and ::after pseudo-elements

### LINKED ISSUE #12: the ::before and ::after pseudo-elements got an empty pseudo name

### PR DESCRIPTION
**Pull request by elad-yosifon**
fixes #12

### CODE REVIEW

**Comment by mdevils** [comment]
@elad-yosifon thank you for your contribution!

I checked your PR and I think it will be a bit inconsistent with CSS spec and not so comfortable to use for the end-users.

Can I suggest a different approach?

Currently we have `preudos` array which as of today can only contain pseudo-classes:

```js
pseudos: [ { name: 'lt', valueType: 'substitute', value: 'var' } ],
```

What if we extend it a bit?

```js
pseudos: [
  { type: 'pseudoClass', name: 'lt', valueType: 'substitute', value: 'var' },
  { type: 'pseudoElement', name: 'after' }
],
```

What do you think?

**Comment by elad-yosifon** [comment]
@mdevils the first thing that comes into mind is backwards compatibility.. 
IMO this issue is a `parsing issue`, not a code breaking bug (assuming the end user is parsing and rendering using the lib utilities).

My initial thought was to fix the parser and "patch" the rendering utility in a backwards compatible way..

**Comment by mdevils** [comment]
@elad-yosifon thank you for your fast response.

Backwards-compatibility is very to implement in this case. If `type` is missing, `pseudoClass` is implied.

My point is that pseudo-class and pseudo-element have different nature. For instance, pseudo element cannot have an argument or round braces after it. So they should be parsed differently. I.e. `div::after(hello)` should be a syntax error.

**Comment by mdevils** [comment]
Hello @elad-yosifon. After a huge refactoring version `2.0.0` was released, which doesn't have this problem anymore. Please update.

**Pull request closed without merging**
