### PR TITLE
add case sensitivity checks

### PR DESCRIPTION
**Pull request by grmoon**
Added case sensitivity checks per issue #15.
Added tests similar to existing attribute selector tests using case insensitivity.

### CODE REVIEW

**Comment by mdevils** [comment]
Thank you for your contribution. I will soon use your code and adapt it to the codebase.

**Comment by straker** [comment]
I know this is a bit old, but is there any way to get this into the codebase? Would love to be able to do case insensitive selectors.

**Comment by mdevils** [comment]
Thank for reminding. I'll take a look soon.

**Comment by mdevils** [comment]
Hello @grmoon, after a huge refactoring version `2.0.0` was released, which now has this feature implemented. Please update.

**Pull request closed without merging**
